apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volunteerhub-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/KwangZung/volunteer-hub.git' # Đảm bảo đây là link repo gốc của bạn
    targetRevision: main
    path: charts/volunteerhub
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: volunteerhub-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true