apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-backend-monitor
  labels:
    release: prometheus # Chú ý: Label này phụ thuộc vào tên release cấu hình kube-prometheus-stack của bạn
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics